import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
public class zestaw1 {
    public static void main(String[] args){
        String imie = "Marcin";
        String nazwisko = "Miszta";
        System.out.print("\n1)");
        System.out.print(imie + nazwisko);
        System.out.print("\n2)");
        System.out.print("\n"+imie.length()+"\n");
        System.out.print(nazwisko.length()+"\n");
        System.out.print("3)");
        String wyraz1 = "Ala";
        String wyraz2 = "ma";
        String wyraz3 = "kota";
        System.out.print(wyraz1+wyraz2+wyraz3);
        System.out.println("\n4)");
        System.out.println("                    * " ); ;
        System.out.println("                    * * " ); ;
        System.out.println("                    * * * " );
        System.out.println("* * * * * * * * * * * * * * ");
        System.out.println("* * * * * * * * * * * * * * *");
        System.out.println("* * * * * * * * * * * * * * ");
        System.out.println("                    * * * " );
        System.out.println("                    * * " ); ;
        System.out.println("                    * " ); ;

        System.out.println("      *     ");
        System.out.println("     * *    ");
        System.out.println("    * * *   ");
        System.out.println("   * * * *  ");
        System.out.println("  * * * * * ");
        System.out.println(" * * * * * *");
        System.out.println("  * * * * * ");
        System.out.println("   * * * *  ");
        System.out.println("    * * *   ");
        System.out.println("     * *    ");
        System.out.println("      *     " );

        System.out.println("5)");
        String zdanie = "Ala ma kota";
        zdanie = zdanie.replaceAll("a", "e");
        System.out.println(zdanie);
        System.out.println("6)");
        String zdanie2 = "Ala ma kota";
        String zdanieUp = zdanie2.toUpperCase();
        System.out.println(zdanieUp);
        String zdanieLo = zdanie2.toLowerCase();
        System.out.println(zdanieLo);
        System.out.println("7)");
        int ascivalue1 = 'A';
        int ascivalue2 = '!';
        int ascivalue3 = '@';
        int ascivalue4 = '>';
        int ascivalue5 = '~';
        int ascivalue6 = '\n';
        int ascivalue7 = '\b';
        System.out.println("A: "+ascivalue1);
        System.out.println("!: "+ascivalue2);
        System.out.println("@: "+ascivalue3);
        System.out.println(">: "+ascivalue4);
        System.out.println("~: "+ascivalue5);
        System.out.println("\\n: "+ascivalue6);
        System.out.println("\\b: "+ascivalue7);
        System.out.println("8)");
        System.out.println("Cyfry: 48-57");
        System.out.println("Duże litery: 65-90");
        System.out.println("Małe litery: 97-122");
        System.out.println("9)");
        String w1 = "jego pupil";
        String w2 = "zwierzęciem";
        String w3 = "rozmiar";
        System.out.printf("Grzesiek nie wiedział dlaczego %s jest tak drapieżnym %s mimo, że jego %s na to nie wskazuje.",w1,w2,w3);
        System.out.println("\n10)");
        String w4 = "Sapiens";
        String w5 = "Juwal Noach Harari";
        System.out.printf("%s to najlepsza książka napisana przez %s",w4, w5);
        System.out.println("\n11)");
        String slowo = "wodrze";
        String slowa = slowo.repeat(5);
        System.out.println(slowa);
        System.out.println("\n12)");
        LocalDateTime czas = LocalDateTime.now();
        DateTimeFormatter czasf = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss");
        String formattedTime = czas.format(czasf);
        System.out.println("Dzisiaj jest "+formattedTime);
        char l1 = 54;
        char l2 = 103;
        char l3 = 241;
        char l4 = 67;
        char l5 = 9999;
        char l6 = 12;
        char l7 = (char) 155706;
        System.out.println("54: "+l1);
        System.out.println("103: "+l2);
        System.out.println("241: "+l3);
        System.out.println("67: "+l4);
        System.out.println("9999: "+l5);
        System.out.println("12: "+l6);
        System.out.println("155706: "+l7);

    }
}
